name: Staging Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug
          extensions: grpc
      - name: Get extensions cache directory
        id: extensions-cache
        # run: echo "::set-output name=dir::$(php -r "echo ini_get('extension_dir');")"
        run: echo "dir=$(php -r "echo ini_get('extension_dir');")" >> ${GITHUB_OUTPUT}
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extensions-cache.outputs.dir }}
          key: ${{ runner.os }}-extensions-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-extensions-${{ hashFiles('**/composer.lock') }}
  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy-staging
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: api-user@stg.cashingames.com
          FTP_PASSWORD: ${{ secrets.STG_FTP_PASSWORD }}
